// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutUsDocumentDataSlicesSlice = TeamandtextSlice;

type AboutUsDocumentDataSlices1Slice = TeamandtextSlice;

/**
 * Content for About us documents
 */
interface AboutUsDocumentData {
  /**
   * Slice Zone field in *About us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice>; /**
   * Meta Title field in *About us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *About us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices1: prismic.SliceZone<AboutUsDocumentDataSlices1Slice>;
}

/**
 * About us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

type Aboutus2DocumentDataSlicesSlice = TeamandtextSlice;

/**
 * Content for AboutUs2 documents
 */
interface Aboutus2DocumentData {
  /**
   * Slice Zone field in *AboutUs2*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus2.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<Aboutus2DocumentDataSlicesSlice>;
}

/**
 * AboutUs2 document from Prismic
 *
 * - **API ID**: `aboutus2`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Aboutus2Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<Aboutus2DocumentData>,
    "aboutus2",
    Lang
  >;

/**
 * Content for navbar documents
 */
interface NavbarDocumentData {
  /**
   * about_us field in *navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.about_us
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  about_us: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Read more field in *navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.read_more
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  read_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;

type PageDocumentDataSlicesSlice =
  | TeamandtextSlice
  | IntrotextSlice
  | NavbarSlice
  | SlidesImagesSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * about_us_link field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: About us
   * - **API ID Path**: page.about_us_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  about_us_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * heroImage field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.heroimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  heroimage: prismic.ImageField<never>;

  /**
   * button to next page field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button_to_next_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_to_next_page: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | AboutUsDocument
  | Aboutus2Document
  | NavbarDocument
  | PageDocument;

/**
 * Primary content in *Introtext → Default → Primary*
 */
export interface IntrotextSliceDefaultPrimary {
  /**
   * main_text field in *Introtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: introtext.default.primary.main_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_text: prismic.RichTextField;

  /**
   * text field in *Introtext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: introtext.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * text2 field in *Introtext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: introtext.default.primary.text2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text2: prismic.KeyTextField;

  /**
   * Read more field in *Introtext → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: introtext.default.primary.read_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  read_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Introtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntrotextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntrotextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Introtext*
 */
type IntrotextSliceVariation = IntrotextSliceDefault;

/**
 * Introtext Shared Slice
 *
 * - **API ID**: `introtext`
 * - **Description**: Introtext
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntrotextSlice = prismic.SharedSlice<
  "introtext",
  IntrotextSliceVariation
>;

/**
 * Primary content in *Navbar → Default → Primary*
 */
export interface NavbarSliceDefaultPrimary {
  /**
   * logo field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * aboutus field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.aboutus
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  aboutus: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Read more field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.read_more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  read_more: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault;

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavbarSlice = prismic.SharedSlice<"navbar", NavbarSliceVariation>;

/**
 * Primary content in *SlidesImages → Default → Primary*
 */
export interface SlidesImagesSliceDefaultPrimary {
  /**
   * imageslides field in *SlidesImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_images.default.primary.imageslides
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imageslides: prismic.ImageField<"image2" | "image3">;

  /**
   * image2 field in *SlidesImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_images.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image2: prismic.ImageField<never>;

  /**
   * image3 field in *SlidesImages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slides_images.default.primary.image3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image3: prismic.ImageField<never>;
}

/**
 * Default variation for SlidesImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SlidesImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlidesImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SlidesImages*
 */
type SlidesImagesSliceVariation = SlidesImagesSliceDefault;

/**
 * SlidesImages Shared Slice
 *
 * - **API ID**: `slides_images`
 * - **Description**: SlidesImages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SlidesImagesSlice = prismic.SharedSlice<
  "slides_images",
  SlidesImagesSliceVariation
>;

/**
 * Primary content in *Teamandtext → Default → Primary*
 */
export interface TeamandtextSliceDefaultPrimary {
  /**
   * imageteam field in *Teamandtext → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teamandtext.default.primary.imageteam
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imageteam: prismic.ImageField<never>;

  /**
   * team field in *Teamandtext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teamandtext.default.primary.team
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  team: prismic.KeyTextField;

  /**
   * texta bout field in *Teamandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teamandtext.default.primary.texta_bout
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texta_bout: prismic.RichTextField;
}

/**
 * Default variation for Teamandtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamandtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamandtextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Teamandtext*
 */
type TeamandtextSliceVariation = TeamandtextSliceDefault;

/**
 * Teamandtext Shared Slice
 *
 * - **API ID**: `teamandtext`
 * - **Description**: Teamandtext
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamandtextSlice = prismic.SharedSlice<
  "teamandtext",
  TeamandtextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      AboutUsDocumentDataSlices1Slice,
      Aboutus2Document,
      Aboutus2DocumentData,
      Aboutus2DocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      IntrotextSlice,
      IntrotextSliceDefaultPrimary,
      IntrotextSliceVariation,
      IntrotextSliceDefault,
      NavbarSlice,
      NavbarSliceDefaultPrimary,
      NavbarSliceVariation,
      NavbarSliceDefault,
      SlidesImagesSlice,
      SlidesImagesSliceDefaultPrimary,
      SlidesImagesSliceVariation,
      SlidesImagesSliceDefault,
      TeamandtextSlice,
      TeamandtextSliceDefaultPrimary,
      TeamandtextSliceVariation,
      TeamandtextSliceDefault,
    };
  }
}
