// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  introtext: dynamic(() => import("./Introtext")),
  navbar: dynamic(() => import("./Navbar")),
  slides_images: dynamic(() => import("./SlidesImages")),
  teamandtext: dynamic(() => import("./Teamandtext")),
};
